server:
  port: 8161

spring:
  application:
    name: eureka-service

  config:
    import: "optional:configserver:http://localhost:8105"
    name: eureka-service
    profile: default

  security:
    oauth2:
      client:
        registration:
          eureka-service:
            client-id: eureka-service
            client-secret: YWJhLWV1cmVrYS1zZXJ2aWNl
            authorization-grant-type: client_credentials
            provider: eureka-service
        provider:
          eureka-service:
            token-uri: http://localhost:8000/oauth2/token

      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/oauth2/jwks

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
