version: "3.9"

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ./nfs-data:/data
    ports:
      - "2049:2049"
      - "111:111"
      - "20048:20048"
    restart: unless-stopped
    user: root
    command: >
      sh -c "
        adduser -D -h /home/aba -s /bin/sh aba &&
        echo 'aba:aba' | chpasswd &&
        chown -R aba:aba /data &&
        /entrypoint.sh
      "

networks:
  nfs-net:
    driver: bridge

volumes:
  nfs_share:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfs-server,vers=4,soft"
      device: ":/data"
