server:
  port: 8188

spring:
  application:
    name: aba-file-service

jwt:
  secret: f8c2d6b3de83a72a3584c29fd29cc29fc91423736e21ea0450d0b6fb6e9e29bf
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8161/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
    preferIpAddress: true

file:
  nfs:
    path: /data
  thumbnail:
    size: 300
