spring:
  application:
    name: aba-authorization-service

  cloud:
    config:
      uri: http://localhost:8105
      fail-fast: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000

server:
  port: 8000

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          service-client:
            client-id: service-client
            client-secret: secret
            scope: service.read
            authorization-grant-type: client_credentials
            provider: local-provider
        provider:
          local-provider:
            token-uri: http://localhost:8000/oauth2/token
