spring:
  application:
    name: aba-gateway-service
  security:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: aba-auth-auth
          uri: lb://ABA-AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
        - id: aba-auth-user
          uri: lb://ABA-AUTHENTICATION-SERVICE
          predicates:
            - Path=/user/**
        - id: aba-report-service
          uri: lb://ABA-REPORT-SERVICE
          predicates:
            - Path=/api/report/**
          filters:
            - AuthenticationFilter
        - id: aba-service
          uri: lb://ABA-SERVICE
          predicates:
            - Path=/api/aba/**
          filters:
            - AuthenticationFilter
          
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8161/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
    preferIpAddress: true

jwt:
  secret: f8c2d6b3de83a72a3584c29fd29cc29fc91423736e21ea0450d0b6fb6e9e29bf

server:
  port: 8184
